version: "3.9"

services:
  mq-productor-rutas:
    container_name: productor-rutas
    build:
      context: ./ms-productor-rutas-vehiculos
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - app-network

  mq-consumidor-rutas:
    container_name: consumidor-rutas
    build:
      context: ./ms-consumidor-rutas-vehiculos
      dockerfile: Dockerfile
    ports:
      - "81:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
